version: '3'
    
services:
  db:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - ./data/db:/data/db 
  api:
    build: ./velhia.api
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  web:
    build:
      context: ./velhia.web
    ports:
      - "5000:5000"
    depends_on: 
      - api
  play:
    build: ./velhia.game
    command: python main.py
    links:
      - api
    depends_on: 
      - api
