version: '3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    networks:
      - velhia
  ovomaltino-api:
    image: ovomaltino/api-mongo:1.0.0
    restart: always
    ports:
      - "3005:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      - velhia
  velhia-api:
    build: ./velhia.api
    restart: always
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      - velhia
  velhia-play:
    build: ./velhia.game
    restart: always
    network_mode: host
    volumes:
      - /logs/:/logs/
    depends_on:
      - velhia-api
      - ovomaltino-api

networks:
  velhia:
