version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=velhia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes: 
      - velhia:/var/lib/postgresql/data
  api:
    build: ./velhia.api
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/Velh-IA-api
    ports:
      - "5000:5000"
    depends_on:
      - db
  web:
    build:
      context: ./velhia.web
    command: npm start
    volumes:
      - ./velhia.web:/app
    ports:
      - "3000:3000"

volumes: 
  velhia: