# Generated by Django 3.0.8 on 2020-07-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='country')),
                ('name', models.TextField()),
                ('country_code', models.TextField(unique=True)),
                ('currencyId', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='currency')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='language')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='region')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='player')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('genre', models.TextField()),
                ('age', models.IntegerField()),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'verbose_name_plural': 'Player',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='languageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='regionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region'),
        ),
    ]
