apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ovomaltino-api
  name: ovomaltino-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ovomaltino-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovomaltino-api
    spec:
      containers:
      - image: ovomaltino/api-mongo:1.0.0
        imagePullPolicy: IfNotPresent
        name: ovomaltino-api
        ports:
        - name: liveness-port
          containerPort: 3005
        env:
          - name: PORT
            value: "3005"
          - name: DATABASE_CONNECTION_STRING
            value: mongodb://mongo-db/ovomaltino
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovomaltino-api
  name: ovomaltino-api
  namespace: default
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: ovomaltino-api
  sessionAffinity: None
  type: NodePort