apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: velhia-api
  name: velhia-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: velhia-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: velhia-api
    spec:
      containers:
      - image: ccr5/velhiaapi
        imagePullPolicy: IfNotPresent
        name: velhia-api
        ports:
        - name: liveness-port
          containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: DATABASE_CONNECTION_STRING
            value: mongodb://mongo-db/velhia
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: velhia-api
  name: velhia-api
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: velhia-api
  sessionAffinity: None
  type: NodePort