apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: velhia-play
  name: velhia-play
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velhia-play
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: velhia-play
    spec:
      containers:
      - image: ccr5/velhiaplay
        imagePullPolicy: IfNotPresent
        name: velhia-play
        ports:
          - name: liveness-port
            containerPort: 3000
        env:
          - name: API_ADDRESS
            value: http://velhia-api/
          - name: API_VERSION
            value: v1
          - name: COLLECTIONS
            value: "matchs,algorithms"
          - name: OVOMALTINO_API_ADDRESS
            value: http://ovomaltino-api/
          - name: OVOMALTINO_API_VERSION
            value: v1
          - name: OVOMALTINO_API_PORT
            value: "3005"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: velhia-play
  name: velhia-play
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  selector:
    app: velhia-play
  sessionAffinity: None
  type: LoadBalancer